services:
  app-1:
    build: .
    hostname: app-1
    environment:
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - backend
      - payment-processor

  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  web:
    image: nginx:1.28-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - app-1

networks:
  backend:
    driver: bridge

  payment-processor:
    external: true
