x-service-templates:
  &app
  build: .
  depends_on:
    - redis
  volumes:
    - ./app:/app
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.6"
        memory: "90MB"

services:
  app-1:
    <<: *app
    hostname: app-1

  app-2:
    <<: *app
    hostname: app-2
    command: /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf

  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  web:
    image: nginx:1.28-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - app-1
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "150MB"

networks:
  backend:
    driver: bridge

  payment-processor:
    external: true
